# fly.toml app configuration file for easycod-dz-staging Shopify app
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "easycod-dz-staging"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "staging"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[processes]
  app = "npx prisma migrate deploy && npm run start"

[deploy]
  release_command = "npx prisma migrate deploy"
  strategy = "immediate"

# Health check configuration
[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/ping"

# Staging-specific static file serving
[[statics]]
  guest_path = "/public"
  url_prefix = "/public"
