# fly.toml app configuration file generated for easycod-dz-bitter-darkness-8320 on 2025-10-11T20:01:44+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'easycod-dz-bitter-darkness-8320'
primary_region = 'fra'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  SHOPIFY_API_KEY = "78b3b49a43d2ac2ca7e3abaf380e011d"
  SHOPIFY_API_SECRET = "cf24bd7dc35faadf8b645cdee12803f3"
  SHOPIFY_APP_URL = "https://easycod-dz-bitter-darkness-8320.fly.dev/"
  SCOPES = "read_draft_orders,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_orders,read_products,write_draft_orders,write_metaobject_definitions,write_metaobjects,write_online_store_pages,write_orders,write_products"
