services:
  - type: web
    name: easycod-dz
    env: node
    plan: free
    buildCommand: "npm install && npx prisma generate && npm run build"
    startCommand: "node server.js"
    healthCheckPath: "/health"
    # Environment variables should be set in the Render dashboard
    # DO NOT hardcode sensitive values in this file
    # Set these environment variables in the Render dashboard:
    # - SHOPIFY_API_KEY: Your Shopify app's API key
    # - SHOPIFY_API_SECRET: Your Shopify app's API secret
    # - SHOPIFY_APP_URL: Your app's URL (e.g., https://easycod-dz-1.onrender.com) - OPTIONAL, has fallback
    # - SCOPES: Comma-separated list of Shopify scopes
    # - DATABASE_URL: Get this from the database service's "Internal Database URL" (must include ?sslmode=require)
    # - SESSION_SECRET: A long, random string for session security

  - type: pserv
    name: easycod-dz-db
    plan: free
    databaseName: easycod_dz
    user: easycod_dz_user