services:
  - type: web
    name: easycod-dz
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node server.js"
    # Environment variables should be set in the Render dashboard
    # DO NOT hardcode sensitive values in this file
    # The following are non-sensitive defaults:
    envVars:
      - key: NODE_VERSION
        value: "20.11.0"
      - key: NODE_ENV
        value: "production"
    # Required Shopify environment variables (set these in Render dashboard):
    # - SHOPIFY_API_KEY: Your Shopify app's API key
    # - SHOPIFY_API_SECRET: Your Shopify app's API secret
    # - SHOPIFY_APP_URL: Your app's URL (e.g., https://your-app.onrender.com)
    # - SCOPES: Comma-separated list of Shopify scopes
    # - DATABASE_URL: Your database connection string (if using external DB)