services:
  - type: web
    name: easycod-dz
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        sync: false
      - key: SCOPES
        value: read_products,write_orders,read_orders,write_checkouts,read_checkouts
      - key: HOST
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
    healthCheckPath: /ping
    autoDeploy: true
    branch: main

databases:
  - name: easycod-postgres
    plan: free
    databaseName: easycod_db
    user: easycod_user
