services:
  - type: web
    name: easyood-dz
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node ./build/server/index.js"
    envVars:
      - key: NODE_VERSION
        value: "20.11.0"
      - key: SHOPIFY_API_KEY
        value: 78b3b49e43d2ac2ca7e3aba1308e911d
      - key: SHOPIFY_APP_URL
        value: https://easyood-dz.onrender.com
      - key: SCOPES
        value: "read_draft_orders,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_orders,read_products,write_draft_orders,write_metaobject_definitions,write_metaobjects,write_online_store_pages,write_orders,write_products"
      # --- DEBUGGING STEP ---
      # Temporarily add a placeholder secret here to test env var loading.
      - key: SHOPIFY_API_SECRET
        value: "this-is-a-test-not-the-real-secret"