services:
  - type: web
    name: easycod-dz
    env: node
    plan: free
    buildCommand: npm install && npm run setup && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        value: https://easycod-dz.onrender.com
      - key: SCOPES
        value: read_draft_orders,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_products,read_orders,write_draft_orders,write_metaobject_definitions,write_metaobjects,write_online_store_pages,write_products,write_orders
      - key: DATABASE_URL
        fromDatabase:
          name: easycod-postgres
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /ping
    autoDeploy: true
    branch: main

databases:
  - name: easycod-postgres
    plan: free
    databaseName: easycod_db
    user: easycod_user
