services:
  - type: web
    name: easycod-dz
    env: node
    plan: free
    buildCommand: "npm install && npx prisma generate && npm run build && npm run setup-db"
    startCommand: "node server.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: easycod-dz-db
          property: connectionString
    # Environment variables should be set in the Render dashboard
    # DO NOT hardcode sensitive values in this file
    # DATABASE_URL is automatically set from the database service below
    # Set these environment variables in the Render dashboard:
    # - SHOPIFY_API_KEY: Your Shopify app's API key
    # - SHOPIFY_API_SECRET: Your Shopify app's API secret
    # - SHOPIFY_APP_URL: Your app's URL (e.g., https://your-app.onrender.com)
    # - SCOPES: Comma-separated list of Shopify scopes

  - type: pserv
    name: easycod-dz-db
    plan: free
    databaseName: easycod_dz
    user: easycod_dz_user