client_id = "78b3b49a43d2ac2ca7e3abaf380e011d"
name = "alma COd"
handle = "alma-cod"
application_url = "https://bouquet-absence-effective-fantasy.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_draft_orders,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_products,write_draft_orders,write_metaobject_definitions,write_metaobjects,write_online_store_pages,write_products"

[auth]
redirect_urls = ["https://bouquet-absence-effective-fantasy.trycloudflare.com/auth/callback", "https://bouquet-absence-effective-fantasy.trycloudflare.com/auth/shopify/callback", "https://bouquet-absence-effective-fantasy.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://bouquet-absence-effective-fantasy.trycloudflare.com"
subpath = "codform"
prefix = "apps"