# Main Application Configuration
client_id = "78b3b49a43d2ac2ca7e3abaf380e011d"
name = "alma COd"
handle = "alma-cod"
application_url = "https://organizational-aqua-blades-plymouth.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
scopes = "read_draft_orders,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_products,write_draft_orders,write_metaobject_definitions,write_metaobjects,write_online_store_pages,write_products"

[auth]
redirect_urls = [
  "https://organizational-aqua-blades-plymouth.trycloudflare.com/auth/callback",
  "https://organizational-aqua-blades-plymouth.trycloudflare.com/auth/shopify/callback",
  "https://organizational-aqua-blades-plymouth.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://organizational-aqua-blades-plymouth.trycloudflare.com"
subpath = "codform"
prefix = "apps"

# Theme Extension Configuration
[[extensions]]
type = "theme"
name = "EasyCOD Form Section"
handle = "easycod-embed"

  # This registers your section file, making it available in the theme editor
  [[extensions.sections]]
  file = "easycod-form-section.liquid"